=== MiriamJimenezIesBelen/LLMM/Tema 4/DTD/Prueba evaluable xml dtd/ejer 3/ejercicio3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre,apellidos,domicilio,telefonos,equipo_deportivo?,aficiones?,comentarios?,evaluaciones)>
<!ATTLIST alumno num_alumno ID #REQUIRED>
<!ATTLIST alumno altura CDATA #IMPLIED>
<!ATTLIST alumno sexo (hombre|mujer) #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefonos (telefono+)>
<!ATTLIST telefono propietario (propio|padre|madre|tutor) #REQUIRED>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT equipo_deportivo (#PCDATA)>
<!ELEMENT aficiones (aficion+)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT comentarios (comentario+)>
<!ELEMENT comentario (#PCDATA)>
<!ELEMENT evaluaciones (evaluacion*)>
<!ATTLIST evaluacion num (primera|segunda|tercera) #REQUIRED>
<!ELEMENT evaluacion (#PCDATA)>

=== MiriamJimenezIesBelen/LLMM/Tema 4/DTD/Prueba evaluable xml dtd/ejer 3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM 'ejercicio3.dtd'>
<alumnos>
    <alumno num_alumno="A1233" altura="165" sexo="hombre">
        <nombre>Juan</nombre>
        <apellidos>Luque Sanz</apellidos>
        <domicilio>Calle Juan Gorostidi</domicilio>
        <telefonos>
            <telefono propietario="padre">684563782 </telefono>
            <telefono propietario="propio">664563780</telefono>
        </telefonos>
        <aficiones>
            <aficion>Leer</aficion>
        </aficiones>
        <comentarios>
            <comentario>Muy trabajador</comentario>
            <comentario>Se pelea muchos con sus compañeros</comentario>
        </comentarios>
        <evaluaciones >
            <evaluacion num="primera">8</evaluacion>
        </evaluaciones>
    </alumno>

    <alumno num_alumno="A4535" >
        <nombre>Ana</nombre>
        <apellidos>Jiménez Ramírez</apellidos>
        <domicilio>Calle San Rafael</domicilio>
        <telefonos>
            <telefono propietario="madre">645667444 </telefono>
        </telefonos>
        <equipo_deportivo>Baloncesto</equipo_deportivo>
        <aficiones>
            <aficion>Videojuegos</aficion>
            <aficion>Piano</aficion>
        </aficiones>
        <evaluaciones>
            <evaluacion num="primera">10</evaluacion>
            <evaluacion num="segunda">7</evaluacion>
            <evaluacion num="tercera">10</evaluacion>
        </evaluaciones>
    </alumno>
</alumnos>
