<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (libros+)>
 <!ELEMENT libros (cod_libro,titulo,editorial,edicion,isbn,num_pag,autor)>
 <!ELEMENT cod_libro (#PCDATA)>
 <!ATTLIST cod_libro cod CDATA #REQUIRED>
 <!ELEMENT titulo (#PCDATA)>
 <!ELEMENT editorial (#PCDATA)>
 <!ATTLIST editorial editor CDATA #REQUIRED>
 <!ELEMENT edicion (#PCDATA)>
 <!ATTLIST edicion anio CDATA #REQUIRED>
 <!ELEMENT isbn (#PCDATA)>
 <!ELEMENT num_pag (#PCDATA)>
 <!ATTLIST num_pag cantidad (largo|medio|corto) #IMPLIED>
 <!ELEMENT autor (#PCDATA)>
 <!ATTLIST autor anio CDATA #IMPLIED>
]>

<biblioteca>
    <libros>
        <cod_libro cod="1">123</cod_libro>
        <titulo>Lenguaje de Marcas</titulo>
        <editorial editor="Javier Zurdo">Ra-Ma</editorial>
        <edicion anio="2008">1</edicion>
        <isbn>9876543212</isbn>
        <num_pag cantidad="largo">300</num_pag>
        <autor anio= "1990">Pablo Rabasco</autor>
    </libros>

    <libros>
        <cod_libro cod="2">456</cod_libro>
        <titulo>Programaci√≥n</titulo>
        <editorial editor="Juan Carlos Moreno">Ra-Ma</editorial>
        <edicion anio="2009">2</edicion>
        <isbn>987321654</isbn>
        <num_pag>450</num_pag>
        <autor>Laura Raya</autor>
    </libros>
</biblioteca>